### ISSUE TITLE
Functionality of C++ headers in libcaercpp/events

### ISSUE THREAD

**Issue by breznak** [inilabs/libcaer#12]
The C++ wrapping code for C headers looks great! :+1: 

I don't know about the state of the cpp headers in `events/` folder. I found a problem, where `common.hpp` is properly defined, but `polarity.hpp` is empty (only the #ifndef). 

I think it should also have the `#include <libcaer/polarity.h>`, or if only the C-header is intended to be used, remove the .hpp broken versions. 

Current status: 
- you include `polarity.h` and everything works
- include `polarity.hpp` and there are undefined names.

**Comment by llongi** [comment]
Yes, the C++ support is still work in progress. The events have now all been ported, as well as pretty much everything else.
Only outstanding job is to write a C++ 'events/packetContainer.hpp' and make the deviceDataGet() functions return that one. I'll complete this Saturday afternoon.

**Comment by llongi** [comment]
C++ support is complete and working. Enjoy!
Some features will be added later, like iterators, but the API should substantially be stable now.

**Comment by breznak** [comment]
Awesome! Thank you very much!

**Comment by llongi** [comment]
Hi, please update again from master. I've just merged a branch with many changes to the C++ support, some of the API changed, but nothing too dramatically. The probably only big user-visible change is that the events are now in the same namespace as the packets, and not inside of the packet namespace.
I've added support for iterators (const & reverse included), properly use smart pointers in the public API now, lots less code duplication between the event packet types, a few new useful methods like front(), back(), etc. and support for negative indexes, so you can do EventPacket[-1] to access the last event and so on (counts back from size(), not capacity()! Is range checked).
for (auto &event : *eventPacket) {} is really nice! ;-)
