### ISSUE TITLE
GCC Requirements?

### ISSUE THREAD

**Issue by aicioara** [inilabs/libcaer#2]
What version if GCC is required to install? I get this error

```
In file included from libcaer/src/davis_common.c:1:0:
libcaer/src/davis_common.h: At top level:
libcaer/src/davis_common.h:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
```

**Comment by llongi** [comment]
Hi, from the README under REQUIREMENTS section:
gcc >= 4.9 or clang >= 3.6
Ubuntu 14.04 is known to still ship GCC 4.8, but it can be easily upgraded, see http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu-14-04 for example.
