### ISSUE TITLE
Makefile for examples

### ISSUE THREAD

**Issue by jo-m** [inilabs/libcaer#24]
Hi all

It would be nice to have some kind of automatic build for the examples directory. At the moment, there are two issues from my point of view:

* Have to build examples manually
* The commands provided in `README` compile with the installed version of the library. What if I want to compile the examples with modifications in my checked out version of libcaer?

The nicest way to solve this would be to create a file `examples/CMakeLists.txt` with contents like
```
include_directories(${LIBCAER_INCDIRS})

add_executable(davis_simple davis_simple.c)

target_link_libraries(davis_simple LINK_PUBLIC caer)
```

However this does not currently work, as the include paths are wrong (installation adds the include prefix `libcaer` and `libcaercpp`).

How do you work around this during development? Any suggestions on how to do this?

**Comment by llongi** [comment]
When testing examples or anything that actually uses the library, we do fully install the library and then compile / test them. This makes sense as you're showing examples of how to use the installed library, and a 'sudo make install' is really not a problematic step in addition. This also catches files not going where they should as a test. The examples are also really basic, only a small starting point, so I believe the manual README compile is fine.
