### ISSUE TITLE
caerDeviceOpen only works when the last digit in the serial number is omitted

### ISSUE THREAD

**Issue by riadix** [inilabs/libcaer#4]
When using the davis ros driver from rpg, I am unable to connect to the DAVIS cameras when I specify the full (8 digit) serial number of the device. Libcaer only seems to find the device when I omit the last digit (even though the call to caerDavisInfoGet returns the correct, full serial number).

**Comment by llongi** [comment]
Yes, this was a bug in the libcaer code. It should be fixed now. Thanks for the report!
