### ISSUE TITLE
Does not work on Raspberry Pi

### ISSUE THREAD

**Issue by jo-m** [inilabs/libcaer#44]
I tried installing and running the libcaer samples on a raspberry pi. I did compile and install from source, as the prebuilt armhf package does not work on Raspberry Pi (See https://wiki.debian.org/RaspberryPi. It does install though.). Compiling and installation works without problems.

I then tried to compile the DAVIS C example:

    gcc -std=c11 -pedantic -Wall -Wextra -O2 -o davis_simple davis_simple.c -D_DEFAULT_SOURCE=1 -lcaer

It runs, but does not detect the connected DAVIS:

    pi@raspb[~/caer]$ ./davis_simple
    2017-11-01 10:34:29 (TZ+0100): DEBUG: davisOpenInternal: Initializing DAVIS.
    2017-11-01 10:34:29 (TZ+0100): CRITICAL: DAVIS ID-1: Failed to open device.
    pi@raspb[~/caer]$

which is listed by lsusb:

    pi@raspb[~/caer]$ lsusb -v
    Bus 001 Device 011: ID 152a:841b Thesycon Systemsoftware & Consulting GmbH
    Couldn't open device, some information will be missing
    Device Descriptor:
      bLength                18
      bDescriptorType         1
      bcdUSB               2.00
      bDeviceClass            0 (Defined at Interface level)
      bDeviceSubClass         0
      bDeviceProtocol         0
      bMaxPacketSize0        64
      idVendor           0x152a Thesycon Systemsoftware & Consulting GmbH
      idProduct          0x841b
      bcdDevice            0.04
      iManufacturer           1
      iProduct                2
      iSerial                 3
      bNumConfigurations      1
      Configuration Descriptor:
        bLength                 9
        bDescriptorType         2
        wTotalLength           25
        bNumInterfaces          1
        bConfigurationValue     1
        iConfiguration          0
        bmAttributes         0x80
          (Bus Powered)
        MaxPower              400mA
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        0
          bAlternateSetting       0
          bNumEndpoints           1
          bInterfaceClass       255 Vendor Specific Class
          bInterfaceSubClass      0
          bInterfaceProtocol      0
          iInterface              0
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x82  EP 2 IN
            bmAttributes            2
              Transfer Type            Bulk
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0200  1x 512 bytes
            bInterval               0

Any ideas? This is not urgent.

**Comment by llongi** [comment]
Hi, that standard ARMv7 packages are incompatible is known, the link you posted explains it, there's nothing we can do there, we use the auto-build support from Launchpad and cannot influence how things are built. But this situation should be well known to anyone using RasPi.
Regarding not finding the device, lsusb's "Couldn't open device, some information will be missing" is key. That means the user you're running as doesn't have permissions to open the device read/write, please add the appropriate udev rules as described in the DAVIS240 user guide. This is a requirement on all Linux systems.
