### ISSUE TITLE
python interface of DAVIS240C

### ISSUE THREAD

**Issue by liwang621** [inilabs/libcaer#49]
There is a file named davis.py. I want use python interface of DAVIS. I already have installed SWIG on Ubuntu 16.04. When I run the build-python-wrapper-py2.sh, some problems have arisen. There is not pyflags_wrap.c. what’s more, also prompted no input file.
![img_2743](https://user-images.githubusercontent.com/34117347/33412684-044608ee-d5c8-11e7-962e-8ff632d1ed66.JPG)

**Comment by llongi** [comment]
Hi, this is the same as https://github.com/inilabs/libcaer/issues/41.
Swig needs to be patched as described there in order for it to work on our files.
I've now submitted a PR to the main Swig repository at swig/swig#1166.
Either get the latest Swig Git code and apply the patch yourself, or wait for it to be merged into the main Swig repo.
