### ISSUE TITLE
Wrong PPA name for installation

### ISSUE THREAD

**Issue by amwhatley** [inilabs/libcaer#57]
The documentation at https://inilabs.com/support/software/libcaer/#h.p1zzhfr49j8 says I should do
`sudo add-apt-repository ppa:llongi/inivation`
but:
`Cannot add PPA: 'ppa:~llongi/ubuntu/inivation'.
The user named '~llongi' has no PPA named 'ubuntu/inivation'
Please choose from the following available PPAs:
 * 'inilabs':  inilabs`

**Comment by llongi** [comment]
Thank you, the correct name for it is still 'inilabs'. A too greedy search&replace was the culprit there. :-)
Fixed now.
