### ISSUE TITLE
Make docs browsable online

### ISSUE THREAD

**Issue by breznak** [inilabs/libcaer#7]
Many projects offer docs online as github pages, this would be very convenient. Eg. https://github.com/zeromq/zmqpp

**Comment by llongi** [comment]
Done. Docs now available at http://inilabs.github.io/libcaer/ also updated PDF at http://inilabs.github.io/libcaer/libcaer_api_manual.pdf

**Comment by breznak** [comment]
..is this hooked to update with new PR to libcaer?

**Comment by llongi** [comment]
No, I'll rebuild them manually as needed for now. libcaer is widely stable. I also don't necessarily want it to always reflect the latest unstable changes until we've figured them out.

**Comment by breznak** [comment]
Ok. 
Reopening as `make doc/pdf` from README does not work..

**Comment by llongi** [comment]
It does here, that's how I generated those docs. Just tried it again, works fine.
Though make doc/pdf support is optional and only works if Doxygen is installed on your system.
Run cmake and check the output there, if it finds it.

**Comment by breznak** [comment]
Sorry, my doxygen is indeed missing. That resolves it. thanks! 
`-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)`
